

INSERT INTO role(id, name) VALUES (1, 'ORGANIZATION');
INSERT INTO role(id, name) VALUES (2, 'USER');

-- STATE DATA
INSERT into state values
(1, 'AL', 'Alabama'),
(2, 'AK', 'Alaska'),
(4,'AZ', 'Arizona'),
(5,'AR', 'Arkansas'),
(6,'CA', 'California'),
(7,'CO', 'Colorado'),
(8,'CT', 'Connecticut'),
(9,'DE', 'Delaware'),
(10, 'DC', 'District of Columbia'),
(11, 'FL', 'Florida'),
(12,'GA', 'Georgia'),
(13, 'HI', 'Hawaii'),
(14, 'ID', 'Idaho'),
(15, 'IL', 'Illinois'),
(16, 'IN', 'Indiana'),
(17, 'IA', 'Iowa'),
(18, 'KS', 'Kansas'),
(19, 'KY', 'Kentucky'),
(20, 'LA', 'Louisiana'),
(21, 'ME', 'Maine'),
(22, 'MD', 'Maryland'),
(23, 'MA', 'Massachusetts'),
(24, 'MI', 'Michigan'),
(25, 'MN', 'Minnesota'),
(26, 'MS', 'Mississippi'),
(27, 'MO', 'Missouri'),
(28, 'MT', 'Montana'),
(29, 'NE', 'Nebraska'),
(30, 'NV', 'Nevada'),
(31, 'NH', 'New Hampshire'),
(32, 'NJ', 'New Jersey'),
(33, 'NM', 'New Mexico'),
(34, 'NY', 'New York'),
(35, 'NC', 'North Carolina'),
(36, 'ND', 'North Dakota'),
(37, 'OH', 'Ohio'),
(38, 'OK', 'Oklahoma'),
(39, 'OR', 'Oregon'),
(40, 'PA', 'Pennsylvania'),
(41, 'PR', 'Puerto Rico'),
(42, 'RI', 'Rhode Island'),
(43, 'SC', 'South Carolina'),
(44, 'SD', 'South Dakota'),
(45, 'TN', 'Tennessee'),
(46, 'TX', 'Texas'),
(47, 'UT', 'Utah'),
(48, 'VT', 'Vermont'),
(49, 'VA', 'Virginia'),
(50, 'WA', 'Washington'),
(51, 'WV', 'West Virginia'),
(52, 'WI', 'Wisconsin'),
(53, 'WY', 'Wyoming');